feat: possibility to create a koson array from a collection
ncomet/koson pull request #5
Opened 2019-04-19 15:01 UTC by achatellier

... and fix tests on windows

2019-04-19 15:11 UTC, achatellier commented
Regarding the line separator, I understand the need to select the right separator when koson produce some data. 
But when processing data from the outside world, koson cannot make assumption about the separator used in strings.

2019-04-22 10:10 UTC, ncomet requested changes
I put some annotations on the files with suggestions, then we can merge ! Thanks !

2019-04-22 10:10 UTC, ncomet commented on src/main/kotlin/com/lectra/koson/Koson.kt
> +    operator fun invoke(elements: Collection<Any?>): ArrayType =
arr() would kind of break the DSL syntax, I suggest
```
   operator fun get(elements: Iterable<Any?>): ArrayType =
        ArrayType(elements.map { toAllowedType(it) }.toList())
```
providing the ability to do

`arr[...]` or `arr[listOf(...)]`

2019-04-22 10:10 UTC, ncomet commented on src/main/kotlin/com/lectra/koson/Koson.kt
> +    operator fun invoke(elements: Collection<Any?>): ArrayType =
And `Iterable` because it is more open

2019-04-22 10:10 UTC, ncomet commented on src/test/kotlin/com/lectra/koson/KosonTest.kt
> +        fun `array with rawjson must be inlined properly in unix format`() {
We also need to test object and array for windows carriage returns inputs

2019-05-07 10:00 UTC, ncomet approved these changes

2019-05-08 07:23 UTC, merged